language: ruby
rvm:
- 2.5.3
script:
- bundle exec rails db:migrate
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: MzGOy7CMMK2wHAakwLfTONa7q4HKmMTqjibxtjR4GwxdlRiPT4mjaExgGbpp0Y2Dr+XiTLi9+1Tc+cYu1iJsMxxYCKXpUdAgPcT7py6wkQwAQRiabMWdrpkGKjtRi9mQyy1GUn2dTbM4HydfFKgQhuUkqZTfOMkdUix0DJoyoBMnpETlR1Zm+KC42jkhdhY+jb4fn/CQ7R5duRD3BmL4DV5Pex7MB1MBOJUK0NxfelmjgAjurDgTE+ur2JvltV6fcBxREUkzUuo1KkiIRt0frRpHaDrHisR3+pRX/R9Y5wObR49lLzyL/cQ0PkpULIrpjqAMhE7WZ4jbxY30mk5vbqy5eHY/7PyxK2Ew2Krmqzpem5NfJTlyjPss+fN1exLLAZXfTFPayc/Ndwfz7SLeHOLgaeZ89AuyWyy/D5DgLlvA4R01DCRGwU1Q1abJ2oAq8yzbFms0EZTlE1BivGpZgQgI1ZU4m2ZHtHIzAnMM5FftD5hd01lYNBKi8eYYJUM9u7EHhW55hStpFXCLn3ry807aVQYcuEZeIGA4r+o9Qyd8tvxDVp6W3fshkKEcd5MPwkpQW0tP4Rq8j11NBSwUddepU9SUTWT4jTNLDFeJEluLRKEWicrFnpEyPpXFYDEMvZBub4LHSCI8lm8eXsSbkwKEYJDrOs8OS9TKY1nZhoE=
  app: LP71-LPA2
  on:
    repo: BHemez/LP71-LPA2
